# Generated by Django 5.1 on 2024-10-04 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('fuente_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapidoysabrosoWEB.url')),
            ],
        ),
        migrations.CreateModel(
            name='PageSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_selector', models.CharField(max_length=255)),
                ('price_selector', models.CharField(max_length=255)),
                ('description_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('image_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapidoysabrosoWEB.url')),
            ],
        ),
    ]
