# Generated by Django 5.1 on 2024-10-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapidoysabrosoWEB', '0005_categoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
