# Generated by Django 5.1.2 on 2024-10-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidoysabrosoWEB', '0007_orden_ordenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
