# Generated by Django 5.1.2 on 2024-10-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidoysabrosoWEB', '0009_marca_remove_producto_logo_alter_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageselector',
            name='logo_selector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
