# Generated by Django 5.1.2 on 2024-10-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapidoysabrosoWEB', '0011_marca_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='logo',
        ),
    ]
