# Generated by Django 5.1.2 on 2024-11-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidoysabrosoWEB', '0014_historialprecio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url_Locales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL de la Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Mapa_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=255, verbose_name='Nombre del Local')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Scraping')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_data', to='rapidoysabrosoWEB.url')),
            ],
        ),
        migrations.CreateModel(
            name='SelectorMAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_selector', models.CharField(max_length=255, verbose_name='Selector CSS para el Local')),
                ('direccion_selector', models.CharField(max_length=255, verbose_name='Selector CSS para la Dirección')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectors', to='rapidoysabrosoWEB.url')),
            ],
        ),
    ]
