# Generated by Django 5.1.2 on 2024-11-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidoysabrosoWEB', '0015_url_locales_mapa_data_selectormapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa_data',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordenadas (Latitud, Longitud)'),
        ),
    ]
