# Generated by Django 5.1.2 on 2024-11-27 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidoysabrosoWEB', '0016_mapa_data_coordenadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapa_data',
            name='url',
        ),
        migrations.AddField(
            model_name='mapa_data',
            name='Marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scraped_data', to='rapidoysabrosoWEB.marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapa_data',
            name='fuente_url_mapa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scraped_data', to='rapidoysabrosoWEB.url_locales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapa_data',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='selectormapa',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectors', to='rapidoysabrosoWEB.url_locales'),
        ),
    ]
